/**:
  ros__parameters:
    enable_button: 0
    
    axis_linear.x: 1
    scale_linear.x: 2.0
    
    axis_angular.yaw: 0
    scale_angular.yaw: 2.0
    
    scale_angular_turbo: 3.0
    
    deadzone: 0.1
 
